#!/bin/sh

clangxx() {
    if [ -f "$_SDK/var/usr/lib/libc++.dylib" ]; then
        clang++ -nostdinc++ -nostdlib++ -isystem "$_SDK/var/usr/include/c++/v1" -lc++ "$@"
    else
        clang++ -stdlib=libstdc++ "$@"
    fi
}

case "$0" in *++) cc='clangxx' ;; esac

target="${0##*/}"
target="${target%-*}"

[ -z "$_SDK" ] && _SDK="$("$target-sdkpath")"
[ -f "${0%/*}/../etc/iphoneports/$target.cfg" ] && minver="$(cat "${0%/*}/../etc/iphoneports/$target.cfg")"

[ -d "$_SDK/var/usr/lib" ] && libflags="-L$_SDK/var/usr/lib"

${cc:-clang} \
    -target "$target" \
    --no-default-config \
    -isysroot "$_SDK" \
    -isystem "$_SDK/var/usr/include" \
    "$libflags" \
    -Wno-unused-command-line-argument \
    -mlinker-version=951.9 \
    "$minver" \
    "$@"
