#!/bin/sh
# shellcheck disable=1090

clangxx() {
    if [ -f "$_SDK/var/usr/lib/libc++.dylib" ]; then
        clang++ -stdlib=libc++ "$@"
    else
        clang++ -stdlib=libstdc++ "$@"
    fi
}

case "$0" in *++) cc='clangxx' ;; esac

target="${0##*/}"
target="${target%-*}"

[ -z "$_SDK" ] && _SDK="$("$target-sdkpath")"
[ -d "$_SDK/var/usr/lib" ] && libflags="-L$_SDK/var/usr/lib"
[ -f "${0%/*}/../etc/iphoneports/$target.cfg" ] && . "${0%/*}/../etc/iphoneports/$target.cfg"

${cc:-clang} \
    -target "$target" \
    --no-default-config \
    -isysroot "$_SDK" \
    -isystem "$_SDK/var/usr/include" \
    -cxx-isystem "$_SDK/var/usr/include/c++/v1" \
    "$libflags" \
    -Wno-unused-command-line-argument \
    -mlinker-version=951.9 \
    "$@"
