#!/bin/sh
# shellcheck disable=1090

case "$0" in
    *++) cc="${0%/*}/../share/iphoneports/bin/clang++" ;;
    *)   cc="${0%/*}/../share/iphoneports/bin/clang"   ;;
esac

target="${0##*/}"
target="${target%-*}"

[ -z "$_SDK" ] && _SDK="$("$target-sdkpath")"
[ -d "$_SDK/var/usr/lib" ] && libflags="-L$_SDK/var/usr/lib"

if [ -f "$_SDK/var/usr/lib/libc++.dylib" ]; then
    stdlib=libc++
else
    stdlib=libstdc++
fi

[ -f "${0%/*}/../etc/iphoneports/$target.cfg" ] && . "${0%/*}/../etc/iphoneports/$target.cfg"

command -v ccache > /dev/null 2>&1 && ccache='ccache'

exec "$ccache" "$cc" \
    -target "$target" \
    -isysroot "$_SDK" \
    -stdlib="$stdlib" \
    -isystem "$_SDK/var/usr/include" \
    -stdlib++-isystem "$_SDK/var/usr/include/c++/v1" \
    "$libflags" \
    -mlinker-version=954.16 \
    "$@" \
    -Wno-unused-command-line-argument
