#!/bin/sh
# shellcheck disable=1090

case $0 in
    *++) cc="${0%/*}/../share/iphoneports/bin/clang++" ;;
    *)   cc="${0%/*}/../share/iphoneports/bin/clang"   ;;
esac

target="${0##*/}"
target="${target%-*}"

[ -z "$_SDK" ] && _SDK="$("$target-sdkpath")"
[ -d "$_SDK/var/usr/lib" ] && libflags="-L$_SDK/var/usr/lib"

stdlib=libc++
if [ -f "$_SDK/var/usr/lib/libc++.dylib" ]; then
    includeflags="-stdlib++-isystem$_SDK/var/usr/include/c++/v1"
elif [ -f "$_SDK/usr/lib/libstdc++.6.dylib" ] || [ -f "$_SDK/usr/lib/libstdc++.6.tbd" ]; then
    stdlib=libstdc++
fi

[ -f "${0%/*}/../etc/iphoneports/$target.cfg" ] && . "${0%/*}/../etc/iphoneports/$target.cfg"

command -v ccache > /dev/null 2>&1 && ccache='ccache'

exec $ccache "$cc" \
    -target "$target" \
    -isysroot "$_SDK" \
    -stdlib="$stdlib" \
    -isystem "$_SDK/var/usr/include" \
    "$includeflags" \
    "$libflags" \
    -mlinker-version=955.13 \
    "$@" \
    -Wno-unused-command-line-argument \
    -Wno-ignored-optimization-argument
